server:
  servlet:
    session:
      timeout: 60m
  port: 8900
#  tomcat:
#    threads:
#      max: 300
#      min-spare: 30
#    max-connections: 30
#    accept-count: 300

spring:
  datasource:
    master:
      hikari:
        username: root
        password: wnsah12
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3500/jmblog_mariadb
        pool-name: jmblog_mariadb_master

    slave:
      hikari:
        username: root
        password: wnsah12
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3501/jmblog_mariadb
        pool-name: jmblog_mariadb_slave

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      ddl-auto: update
      use-new-id-generator-mappings: true
    open-in-view: false

logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace